services:
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
      args:
        - VITE_BASE=/Amudhapuranam/  # GitHub Pages sub-path
    container_name: story-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
